In [1]:
import numpy as np
import Perceptron.perceptron as pn

In [14]:
X = np.array([[1, -1, -1],
              [1, -1, 1],
              [1, 1, -1],
              [1, 1, 1]])

In [15]:
y = np.array([[-1], [1], [1], [-1]])

In [16]:
model = pn.PocketPerceptron(input=3, eta=1, max_iter=1000, rand_seed=None, ignore_flag=True, patience=100)

In [18]:
model.train(X, y)

> /home/joseaguilar/coding/github/McNair-Diochnos-Research/schooner_experiments/Perceptron/perceptron.py(101)train()
     99             index = random.sample(range(len(X)), len(X))
    100             import pdb; pdb.set_trace()
--> 101             E = X[index]
    102             C = y[index]
    103 

ipdb> index = [3, 3, 1, 2, 3, 1, 2, 0]
ipdb> n
> /home/joseaguilar/coding/github/McNair-Diochnos-Research/schooner_experiments/Perceptron/perceptron.py(102)train()
    100             import pdb; pdb.set_trace()
    101             E = X[index]
--> 102             C = y[index]
    103 
    104             if self.learn(E, C):

ipdb> n
> /home/joseaguilar/coding/github/McNair-Diochnos-Research/schooner_experiments/Perceptron/perceptron.py(104)train()
    102             C = y[index]
    103 
--> 104             if self.learn(E, C):
    105                 return
    106             elif np.array_equal(prev_w, self.W):

ipdb> s
--Call--
> /home/joseaguilar/coding/github/McNair-Diochnos-R

ipdb> print(self.pi)
[[-1.]
 [-1.]
 [-1.]]
ipdb> print(f'pi: {self.pi}\nrun_pi: {self.run_pi}\nW: {self.W}\nrun_W{self.run_W}')
pi: [[-1.]
 [-1.]
 [-1.]]
run_pi: 0
W: [[0.]
 [0.]
 [0.]]
run_W0
ipdb> print(f'pi: {self.pi}\nrun_pi: {self.run_pi}\nW: {self.W}\nrun_W{self.run_W}')
pi: [[-1.]
 [-1.]
 [-1.]]
run_pi: 0
W: [[0.]
 [0.]
 [0.]]
run_W0
ipdb> n
> /home/joseaguilar/coding/github/McNair-Diochnos-Research/schooner_experiments/Perceptron/perceptron.py(141)learn()
    139         ):
    140 
--> 141         for E, C in zip(X, y):
    142             z = E @ self.pi
    143             pi_C    = -1 if z < 0 else +1

ipdb> n
> /home/joseaguilar/coding/github/McNair-Diochnos-Research/schooner_experiments/Perceptron/perceptron.py(142)learn()
    140 
    141         for E, C in zip(X, y):
--> 142             z = E @ self.pi
    143             pi_C    = -1 if z < 0 else +1
    144             if pi_C == C:

ipdb> n
> /home/joseaguilar/coding/github/McNair-Diochnos-Research/schooner_experime

ipdb> print(f'pi: {self.pi}\nrun_pi: {self.run_pi}\nW: {self.W}\nrun_W: {self.run_W}')
pi: [[-1.]
 [-1.]
 [-1.]]
run_pi: 1
W: [[0.]
 [0.]
 [0.]]
run_W: 0
ipdb> print(self.num_ok_pi)
3
ipdb> print(self.num_ok_W)
4
ipdb> print(np.sign(E @ self.pi))
[-1.]
ipdb> print(np.sign(X @ self.pi))
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]]
ipdb> print(self.solve(X))
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]
ipdb> ax = np.sign(X @ self.pi)
ipdb> ax[ax == 0] = -1
ipdb> ax
array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.]])
ipdb> bx = self.solve(X)
ipdb> ax == y
array([[ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False]])
ipdb> bx == y
array([[ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True]])
ipdb> print(self.num_ok_W)
4
ipdb> c
> /home/joseaguilar/coding/github/McNair-Diochn

In [ ]:
print(f'pi: {self.pi}\nrun_pi: {self.run_pi}\nW: {self.W}\nrun_W: {self.run_W}')

In [ ]:
index = [3, 3, 1, 2, 3, 1, 2, 0]

In [ ]:
np.array([[0.], [0.], [0.]]) # for self.pi, self.W